[workspace]
members = ["common", "config", "service", "tap-agent"]
resolver = "2"

[profile.dev.package."*"]
opt-level = 3

[workspace.dependencies]
alloy = { version = "0.2.1", features = [
    "kzg",
    "signer-mnemonic",
], default-features = false }
clap = "4.4.3"
lazy_static = "1.4.0"
axum = { version = "0.7.5", default-features = false }
tokio = "1.39.2"
prometheus = "0.13.3"
anyhow = { version = "1.0.72", default-features = false }
thiserror = "1.0.49"
async-trait = "0.1.72"
eventuals = "0.6.7"
reqwest = { version = "0.12", features = [
    "charset",
    "h2",
], default-features = false }
serde = { version = "1.0.206", default-features = false }
serde_json = "1.0.124"
sqlx = { version = "0.7.2", features = [
    "bigdecimal",
    "chrono",
    "json",
    "macros",
    "migrate",
    "postgres",
    "runtime-tokio",
    "rust_decimal",
], default-features = false }
tracing = { version = "0.1.40", default-features = false }
bigdecimal = "0.4.3"
build-info = "0.0.38"
tap_core = { git = "https://github.com/semiotic-ai/timeline-aggregation-protocol", rev = "ff856d9", default-features = false }
tracing-subscriber = { version = "0.3", features = [
    "json",
    "env-filter",
], default-features = false }
thegraph-core = { git = "https://github.com/edgeandnode/toolshed", rev = "85ee00b", features = [
    "subgraph-client",
] }
thegraph-graphql-http = "0.2.0"
