[package]
name = "test-vector"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy.workspace = true
bip39 = "2.0.0"
lazy_static.workspace = true
tap_core.workspace = true
thegraph-core.workspace = true
