[package]
name = "indexer-watcher"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true, features = ["macros", "rt", "time", "sync"] }
tracing.workspace = true
anyhow.workspace = true
