[package]
name = "service"
version = "0.1.0"
edition = "2021"
description="Could not find crate on crates.io and could not import with git and path at the same time, so copied a version directly at https://github.com/graphprotocol/indexer/blob/972658b3ce8c512ad7b4dc575d29cd9d5377e3fe/packages/indexer-native/native"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexer-common = { path = "../common" }
confy = "0.5.1"
ethers-core = "2.0.10"
ethers = "2.0.10"
eventuals = "0.6.7"
dotenvy = "0.15"
log = "0.4.17"
anyhow = "1.0.57"
reqwest = "0.11.10"
tokio = { version = "1", features = ["rt", "macros", "sync", "full"] }
tracing = "0.1.34"
thiserror = "1.0.49"
serde = { version = "1.0", features = ["rc", "derive"] }
serde_json = "1"
axum = "0.5"
hyper = "0.14.27"
tower = { version = "0.4", features = ["util", "timeout", "limit"] }
tower-http = { version = "0.4.0", features = ["add-extension", "trace", "cors"] }
toml = "0.7.4"
once_cell = "1.17"
async-graphql = "4.0.16"
async-graphql-axum = "4.0.16"
sha3 = "0.10.6"
tracing-subscriber = { version = "0.3", features = [
    "env-filter",
    "ansi",
    "fmt",
    "std",
    "json",
] }
autometrics = { version = "0.3.3", features = ["prometheus-exporter"] }
clap = { version = "4.3.1", features = ["derive", "env"] }
prometheus = "0.13.3"
hex = "0.4.3"
tap_core = "0.5.1"
ethereum-types = "0.14.1"
sqlx = { version = "0.7.1", features = ["postgres", "runtime-tokio", "bigdecimal", "rust_decimal", "time"] }
alloy-primitives = { version = "0.3.3", features = ["serde"] }
alloy-sol-types = "0.3.2"
lazy_static = "1.4.0"
toolshed = { git = "https://github.com/edgeandnode/toolshed", branch = "main", features = ["graphql"] }

[dev-dependencies]
faux = "0.1.10"
hex-literal = "0.4.1"
indexer-common = { path = "../common", features = ["mock"] }
test-log = "0.2.12"
wiremock = "0.5.19"

# [[bin]]
# name = "indexer-native"
# path = "native"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
# Disable features which are enabled by default
features = ["precommit-hook", "run-cargo-fmt", "run-cargo-clippy"]
