[package]
name = "indexer-tap-agent"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "indexer-tap-agent"
path = "src/main.rs"

[dependencies]
alloy-primitives = "0.6"
alloy-sol-types = "0.6"
anyhow = "1.0.72"
async-trait = "0.1.72"
bigdecimal = { version = "0.4.2", features = ["serde", "string-only"] }
clap = { version = "4.4.3", features = ["derive", "env"] }
ethereum-types = "0.14.1"
eventuals = "0.6.7"
log = "0.4.19"
prometheus = "0.13.3"
axum = "0.7.5"
futures-util = "0.3.28"
indexer-common = { version = "0.1.0", path = "../common" }
jsonrpsee = { version = "0.20.2", features = ["http-client", "macros"] }
lazy_static = "1.4.0"
reqwest = "0.12"
serde = "1.0.188"
serde_json = "1.0.104"
serde_yaml = "0.9.25"
sqlx = { version = "0.7.2", features = [
    "postgres",
    "runtime-tokio",
    "bigdecimal",
    "rust_decimal",
    "chrono",
] }
tap_aggregator = "0.3.0"
tap_core = "0.8.0"
thiserror = "1.0.44"
tokio = { version = "1.33.0" }
thegraph = { git = "https://github.com/edgeandnode/toolshed", tag = "thegraph-v0.5.0" }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3", features = [
    "env-filter",
    "ansi",
    "fmt",
    "std",
    "json",
] }
ractor = "0.9.7"
figment = { version = "0.10.19", features = ["toml"] }
shellexpand = { version = "3.1.0", default-features = false, features = ["base-0"] }

[dev-dependencies]
ethers-signers = "2.0.8"
tempfile = "3.8.0"
wiremock = "0.5.19"
futures = "0.3.30"
serde_assert = "0.7.1"
toml = "0.8.13"
