[package]
name = "indexer-tap-agent"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "indexer-tap-agent"
path = "src/main.rs"

[dependencies]
alloy-primitives = "0.6"
alloy-sol-types = "0.6"
anyhow = "1.0.72"
async-trait = "0.1.72"
bigdecimal = "0.4.2"
clap = { version = "4.4.3", features = ["derive", "env"] }
confy = "0.5.1"
dotenvy = "0.15.7"
ethereum-types = "0.14.1"
eventuals = "0.6.7"
indexer-common = { version = "0.1.0", path = "../common" }
jsonrpsee = { version = "0.20.2", features = ["http-client", "macros"] }
lazy_static = "1.4.0"
reqwest = "0.11.20"
serde = "1.0.188"
serde_json = "1.0.104"
serde_yaml = "0.9.25"
sqlx = { version = "0.7.2", features = [
    "postgres",
    "runtime-tokio",
    "bigdecimal",
    "rust_decimal",
] }
tap_aggregator = { git = "https://github.com/semiotic-ai/timeline-aggregation-protocol", branch = "aasseman/tap_core_0_7_0_fix_toolshed_dep" }
tap_core = { git = "https://github.com/semiotic-ai/timeline-aggregation-protocol", branch = "aasseman/tap_core_0_7_0_fix_toolshed_dep" }
thiserror = "1.0.44"
tokio = { version = "1.33.0" }
thegraph = { git = "https://github.com/edgeandnode/toolshed", tag = "thegraph-v0.5.0" }
graphql-http = { git = "https://github.com/edgeandnode/toolshed", tag = "graphql-http-v0.2.1" }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3", features = [
    "env-filter",
    "ansi",
    "fmt",
    "std",
    "json",
] }
enum-as-inner = "0.6.0"
open-fastrlp = "0.1.4"
ethers = "2.0.13"

[dev-dependencies]
ethers-signers = "2.0.8"
tempfile = "3.8.0"
wiremock = "0.5.19"
