# You will have to change *all* the values below to match your setup.
#
# Some of the config below are global graph network values, which you can find here:
# https://github.com/graphprotocol/indexer/tree/main/docs/networks
#
# Pro tip: if you need to load some values from the environment into this config, you
# can use shell expansions with environment variables. Example:
# postgres_url = "postgresql://indexer:${POSTGRES_PASSWORD}@postgres:5432/indexer_components_0"

[ethereum]
indexer_address = "0x0000000000000000000000000000000000000000"

[receipts]
# The chain ID of the network that the graph network is running on
# Should be the same as the chain ID of the network that the graph network is running on
receipts_verifier_chain_id = 123546
# Contract address of TAP's receipt aggregate voucher (RAV) verifier.
receipts_verifier_address = "0x1111111111111111111111111111111111111111"

[indexer_infrastructure]
graph_node_query_endpoint = "http://graph-node:8030/graphql"
graph_node_status_endpoint = "http://graph-node:8000"

# Credentials for the postgres database used for the indexer components. The same database
# that is used by the `indexer-agent`. It is expected that `indexer-agent` will create
# the necessary tables.
[postgres]
postgres_host = "postgres"
postgres_database = "indexer_components_0"
postgres_username = "indexer"
postgres_password = "let-me-in"

[network_subgraph]
# Optional, deployment to look for in the local `graph-node`, if locally indexed.
# Locally indexing the subgraph is recommended.
network_subgraph_deployment = "Qmaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
# Query URL for the Graph Network subgraph.
network_subgraph_endpoint = "http://example.com/network-subgraph"

[escrow_subgraph]
# Optional, deployment to look for in the local `graph-node`, if locally indexed.
# Locally indexing the subgraph is recommended.
escrow_subgraph_deployment = "Qmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
# Query URL for the Escrow subgraph.
escrow_subgraph_endpoint = "http://example.com/escrow-subgraph"

[tap]
# YAML file with a map of sender addresses to aggregator endpoints.
sender_aggregator_endpoints_file = "endpoints.yaml"
