[metrics]
port = 7300

[subgraphs.network]
syncing_interval_secs = 60
recently_closed_allocation_buffer_secs = 3600

[subgraphs.escrow]
syncing_interval_secs = 60

[service]
serve_network_subgraph = false
serve_escrow_subgraph = false
host_and_port = "0.0.0.0:7600"
url_prefix = "/"

[service.tap]
max_receipt_value_grt = "0.001" # We use strings to prevent rounding errors

[tap.rav_request]
trigger_value_divisor = 10
timestamp_buffer_secs = 60
request_timeout_secs = 5
max_receipts_per_request = 10000
