[package]
name = "indexer-dips"
version = "0.1.0"
edition = "2021"

[features]
default = ["rpc", "db"]
rpc = ["dep:prost", "dep:tonic", "dep:tonic-build", "dep:bytes"]
db = ["dep:sqlx"]

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
build-info.workspace = true
bytes = { version = "1.10.0", optional = true }
derivative = "2.2.0"
futures = "0.3"
http = "0.2"
ipfs-api-backend-hyper = { version = "0.6.0", features = ["with-send-sync"] }
ipfs-api-prelude = { version = "0.6.0", features = ["with-send-sync"] }
prost = { workspace = true, optional = true }
serde.workspace = true
serde_yaml.workspace = true
sqlx = { workspace = true, optional = true }
thegraph-core.workspace = true
thiserror.workspace = true
tokio.workspace = true
tonic = { workspace = true, optional = true }
uuid.workspace = true

[dev-dependencies]
rand = "0.9.0"

[build-dependencies]
tonic-build = { workspace = true, optional = true }
