[package]
name = "indexer-dips"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror.workspace = true
anyhow.workspace = true
alloy-rlp = "0.3.10"
thegraph-core.workspace = true
tonic.workspace = true 
async-trait.workspace = true 
prost.workspace = true 
prost-types.workspace = true 
uuid.workspace = true
base64.workspace = true
tokio.workspace = true

[build-dependencies]
tonic-build = { workspace = true }
