[package]
name = "local-service"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { workspace = true, default-features = true }
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["full"] }
