name: "Lint PR"

on:
  pull_request:

jobs:
  conventional-commits-check:
    name: Check conventional commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5
        with:
          python-version: "3.10"
      - name: Install commitizen
        run: pip install commitizen
      - name: commitizen check
        run: cz check --rev-range ${{ github.event.pull_request.base.sha }}..HEAD
