name: License headers check

on:
  push:
    branches: [ main, dev ]
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: License headers check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Install addlicense
        run: |
          wget https://github.com/google/addlicense/releases/download/v1.1.1/addlicense_1.1.1_Linux_x86_64.tar.gz
          tar -xzf addlicense_1.1.1_Linux_x86_64.tar.gz 
          sudo mv addlicense /usr/local/bin
      - name: Check license headers
        run: >
          addlicense \
            -check \
            -c "Edge & Node, GraphOps, and Semiotic Labs." \
            -l "apache" \
            -s=only \
            -ignore '.github/workflows/*.yml' \
            -ignore '.github/*.yml' \
            -ignore '.github/workflows/*.yaml' \
            -ignore '.github/*.yaml' \
            -ignore 'migrations/*.sql' \
            .
